# This file contains the essential configs for the ingress controller helm chart

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: <CHANGEME>
    resourceGroup: <CHANGEME>
    name: <CHANGEME>

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
# - Option 2: ServicePrincipal as a kubernetes secret
# armAuth:
#   type: servicePrincipal
#   secretName: buildag
#   secretKey: ServicePrincipal.json
armAuth:
    type: aadPodIdentity
    identityResourceID: <CHANGEME>
    identityClientID: <CHANGEME>

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
    enabled: true

################################################################################
# Specify aks cluster related information
aksClusterConfiguration:
    apiServerAddress: <CHANGEME>